# https://docs.netlify.com/configure-builds/file-based-configuration/

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "20.19.0"
  CI = "false"
[context.deploy-preview.environment]
  NODE_VERSION = "20.19.0"
  CI = "false"
[context.branch-deploy.environment]
  NODE_VERSION = "20.19.0"
  CI = "false"
[context.dev.environment]
  NODE_VERSION = "20.19.0"
  CI = "false"
